# Generated by Django 3.1 on 2021-01-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=55)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
